### ISSUE TITLE
Drop down list mandatory validation ignored

### ISSUE THREAD

**Issue by Matthew-Wise** [leekelleher/umbraco-contentment#62]
### What is the current behaviour?

Mandatory dropdown list if left blank passes validation. (tested when using DTGE). Allow empty is set to false.

### What is the expected behaviour?

Validation error is thrown when the list option is empty

### What is the motivation / use case for changing the behaviour?

Ensuring the editor can't make mistakes, which can easily be avoided.

### Please tell us about your set-up:

- Contentment version: [1.1.1]
- Umbraco version: [8.9.1]

**Comment by leekelleher** [comment]
Currently, none of the editors in Contentment have explicit validation, _(as in beyond what Umbraco offers in terms of basic validation)._

The only reason is that I've never figured out how it the client-size AngularJS/Umbraco bits work.
ref: <https://github.com/leekelleher/umbraco-contentment/blob/develop/.github/IDEAS.md#validation>

Definitely something I'd like to add, just not invested any time in making it happen (yet). 😃

**Comment by dawoe** [comment]
@leekelleher I think this one is solved by #81

**Comment by leekelleher** [comment]
@Matthew-Wise Do you see the patch in #81 as the resolution to this issue? If so, cool, let's close it off.
Or was it intended to be more about Contentment editor's validation in general?

**Comment by Matthew-Wise** [comment]
Yeah, looks like that will do it :)

**Comment by leekelleher** [comment]
OK, cool.

I still have a general validation feature review in my own to-do list. (As I have no idea how it actually works in Umbraco, haha!)
